### ISSUE TITLE
Exclude irrelevant data

### ISSUE THREAD

**Issue by rotemb9** [srcole/o-factor#11]
We want to find a way to focus our measures only on relevant papers- e.g. not just abstracts (since some of the papers are not open access and we only have access to the abstract), not reviews, not opinions etc.
We can start with word/characters limitation, but do want to make it more precise.

**Comment by srcole** [comment]
PR #28

**Comment by rotemb9** [comment]
We are removing "papers" which do not have all the relevant sections
