### ISSUE TITLE
test/verify semantic content of keywords

### ISSUE THREAD

**Issue by kristinarapuano** [srcole/o-factor#13]
Evaluate text surrounding keywords/phrases to ensure they are related to open science—e.g., via a classification on semantic vectors (word embeddings) or outlier detection.

**Comment by emilytwood** [comment]
From looking at strings before and after keywords:
- R should be changed to 'R package'
- Add 'MATLAB'
- Add 'repository'
- Add 'publicly available'
- Add separate search for "sequence data can be found" & "sequence data is available"
- Change 'osf' to 'osf.io'
- Remove 'www'
- Change 'datalab' to 'datalad'
