### ISSUE TITLE
Update keywords

### ISSUE THREAD

**Issue by srcole** [srcole/o-factor#4]
The first draft of keywords is preliminary. Some are good and some are bad.

The first example scrape extracted text around each keyword. We should look through these and determine which keywords we want to count in our full scrape.

**Comment by srcole** [comment]
I think looking at the text around "github" will give us some good ideas about what sort of phrases people use like "code is shared at ...", "code is available at...", etc.

**Comment by srcole** [comment]
The strings around each keyword for the preliminary 5000 eLife articles are now available in the data/ directory.

So we can go ahead and start discussing which keywords we should add/remove.

I think we can remove "code is shared" and "protocols.io" because they were not found in any of these articles.

**Comment by rotemb9** [comment]
" R " is not a good one... Maybe R package?

Add "public available"

Add "data are available" not just "data is" (same with code is / codes are available)

**Comment by reznida** [comment]
add "deposited"

**Comment by rosali920** [comment]
R script/s
R software
R 2. or R 3. (to catch listing the version of R)
R function
R statistical language/software/package
performed in R
R version
package in R

**Comment by rosali920** [comment]
I think datalab should be datalad

**Comment by rosali920** [comment]
add repository (?)

**Comment by rosali920** [comment]
add preprint
add *Xiv

**Comment by rotemb9** [comment]
add shell/bash script

add "preprint" and "rxiv" (or "biorxiv"?)
